version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ideas
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ideas
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  cronjob:
    build:
      context: ./backend
    command: ["python", "cron/nightly_runner.py"]
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ideas
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - db
    restart: "no"

volumes:
  db_data:
